networks:
  nginx_default:
    external: true

services:
  onedev:
    image: 1dev/server:latest
    container_name: onedev
    restart: always
    ports:
      - '6610:6610'
      - '6611:6611'
      - '22:22'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - <path/to/containers>/containers/onedev/data:/opt/onedev
    networks:
      - nginx_default