networks:
  nginx_default:
    external: true

services:
  docmost:
    env_file:
      - .env
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: ${APP_URL}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: 'postgresql://docmost:${DB_PASSWORD}@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DIRECTORY}/docmost:/app/data/storage
    networks:
      - nginx_default

  db:
    env_file:
      - .env
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DIRECTORY}/docmost/db_data:/var/lib/postgresql/data
    networks:
      - nginx_default

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - nginx_default

volumes:
  docmost:
  db_data:
  redis_data: